version: '3.9'
services:
  db:
    build:
      context: ./DB
      dockerfile: dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airflow_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  airflow:
    build:
      context: ./airflow
      dockerfile: dockerfile
    depends_on:
      - db
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: mysql+pymysql://root:root@db:3306/airflow_db
    ports:
      - "8081:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: >
      bash -c "airflow db init && airflow webserver & airflow scheduler"

  app:
    build:
      context: ./app
      dockerfile: dockerfile
    depends_on:
      - db
    ports:
      - "8502:8501"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: airflow_db
    volumes:
      - ./app:/app

volumes:
  db_data:
