version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: recommendation_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-airflow_db}
    ports:
      - "3307:3306"
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile # Dockerfile 경로 가정
    container_name: recommendation_app
    env_file:
      - .env
    ports:
      - "8502:8502" # Streamlit 포트
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: ["streamlit", "run", "src/presentation/app.py", "--server.port=8502", "--server.address=0.0.0.0"]

volumes:
  db_data: