# ===================================================================
#          AI TV 추천 시스템: 기본 설정 파일
# ===================================================================
#
# 이 파일에는 프로젝트의 기본 동작을 제어하는 설정을 정의합니다.
# 민감 정보(API 키, 암호 등)는 .env 파일에서 관리합니다.
#

# --- 경로 설정 ---
# 모든 경로는 프로젝트 루트 디렉토리 기준입니다.
paths:
  raw_data_dir: "data/raw/movielens_latest"
  processed_data_path: "data/processed/movielens.parquet"
  log_dir: "logs"
  # 모델 경로는 각 모듈 설정에서 개별적으로 관리합니다.

# --- 페르소나 생성기 설정 ---
persona_generator:
  # 시뮬레이션에 사용할 페르소나 목록
  personas:
    sci_fi_fan:
      name: "SF 매니아"
      description: "공상 과학과 우주, 미래 기술에 대한 깊은 관심을 가진 20대 대학생. 복잡하고 철학적인 서사를 선호합니다."
      favorite_genres: ["Sci-Fi", "Adventure", "IMAX", "Action", "Thriller"]
      watch_history_size: 50
    rom_com_lover:
      name: "로코 홀릭"
      description: "가볍고 즐거운 로맨틱 코미디를 즐겨보는 30대 직장인. 퇴근 후 휴식 시간에 볼 만한 드라마를 찾습니다."
      favorite_genres: ["Romance", "Comedy", "Drama"]
      watch_history_size: 40
    mystery_enthusiast:
      name: "미스터리 탐정"
      description: "추리, 스릴러, 반전이 있는 영화를 찾아보는 것을 즐깁니다. 두뇌 싸움을 하는 콘텐츠를 특히 좋아합니다."
      favorite_genres: ["Mystery", "Thriller", "Crime", "Film-Noir"]
      watch_history_size: 60

  # 가상 평점 생성 시 사용할 분포
  rating_distribution:
    favorite_genre_min: 3.5
    favorite_genre_max: 5.0
    other_genre_min: 2.0
    other_genre_max: 4.0

# --- 평점 예측 모델(NCF) 설정 ---
rating_predictor:
  model_path: "saved_models/ncf_model_latest.pth"
  # 모델 아키텍처 파라미터 (모델 인스턴스화에 필요)
  embedding_dim: 32
  hidden_layers: [64, 32, 16]
  dropout_rate: 0.2

# --- 콘텐츠 라벨러(Gemini) 설정 ---
content_labeler:
  # 사용할 Gemini 모델 이름
  model_name: "gemini-2.5-flash"

  # LLM 응답 생성 관련 설정
  generation_config:
    temperature: 0.5
    top_p: 1.0
    max_output_tokens: 100

  # 시맨틱 라벨 생성을 위한 프롬프트 템플릿
  prompt_template: |
    다음은 특정 영화 또는 TV 프로그램의 제목과 줄거리입니다.
    이 콘텐츠의 핵심적인 주제, 분위기, 소재, 장르, 주요 특징을 나타내는 시맨틱 라벨을 5개에서 7개 사이로 추출해주세요.
    결과는 반드시 쉼표(,)로만 구분된 키워드 리스트 형식으로 응답해야 합니다. 예시: "시간여행, 두뇌싸움, 치밀한구성, 반전, SF스릴러"

    ---
    제목: {title}
    줄거리: {overview}
    ---
    라벨:

# --- 스케줄 크롤러 설정 ---
schedule_crawler:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  # 페이지 로드 및 특정 요소 대기 시간 (초)
  timeout: 30

# --- 추천 엔진(Use Case) 설정 ---
recommendation_engine:
  # 페르소나가 아직 보지 않은 영화 중, 상위 몇 개의 영화에 대해 평점을 예측할지 결정
  top_k_movies_to_predict: 200

  # 예측된 평점이 가장 높은 상위 몇 개의 영화를 '잠재 선호 콘텐츠 클러스터'로 정의할지 결정
  preference_cluster_size: 5

  # 최종 추천을 위한 코사인 유사도 최소 임계값
  similarity_threshold: 0.45

  # 프론트엔드에 표시할 최종 추천 채널의 최대 개수
  max_recommendations_to_show: 10