paths:
  movielens: data/movielens_sample.csv
  embedding_model_name: all-MiniLM-L6-v2
  schedule_cache_dir: data/schedule_cache
personas:
  demo:
    favorite_genres: ['Action', 'Comedy']
default_labels:
  - demo
